---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Configure postfix.
- include: "configure-{{ ansible_os_family }}.yml"
  static: no 